export const specializations = [
  { label: "Cardiologist", value: "cardiologist" },
  { label: "Dentist", value: "dentist" },
  { label: "Dermatologist", value: "dermatologist" },
  { label: "Endocrinologist", value: "endocrinologist" },
  { label: "Gastroenterologist", value: "gastroenterologist" },
  { label: "General Practitioner", value: "general_practitioner" },
  { label: "Gynecologist", value: "gynecologist" },
  { label: "Hematologist", value: "hematologist" },
  { label: "Neurologist", value: "neurologist" },
  { label: "Oncologist", value: "oncologist" },
  { label: "Ophthalmologist", value: "ophthalmologist" },
  { label: "Orthopedist", value: "orthopedist" },
  { label: "Otolaryngologist", value: "otolaryngologist" },
  { label: "Pediatrician", value: "pediatrician" },
  { label: "Psychiatrist", value: "psychiatrist" },
  { label: "Pulmonologist", value: "pulmonologist" },
  { label: "Radiologist", value: "radiologist" },
  { label: "Rheumatologist", value: "rheumatologist" },
  { label: "Urologist", value: "urologist" },
];

export const workDays = [
  { label: "Monday", value: "monday" },
  { label: "Tuesday", value: "tuesday" },
  { label: "Wednesday", value: "wednesday" },
  { label: "Thursday", value: "thursday" },
  { label: "Friday", value: "friday" },
  { label: "Saturday", value: "saturday" },
  { label: "Sunday", value: "sunday" },
];

export const workHours = [
  { label: "09:00", value: "09:00" },
  { label: "09:30", value: "09:30" },
  { label: "10:00", value: "10:00" },
  { label: "10:30", value: "10:30" },
  { label: "11:00", value: "11:00" },
  { label: "11:30", value: "11:30" },
  { label: "12:00", value: "12:00" },
  { label: "12:30", value: "12:30" },
  { label: "13:00", value: "13:00" },
  { label: "13:30", value: "13:30" },
  { label: "14:00", value: "14:00" },
  { label: "14:30", value: "14:30" },
  { label: "15:00", value: "15:00" },
  { label: "15:30", value: "15:30" },
  { label: "16:00", value: "16:00" },
  { label: "16:30", value: "16:30" },
  { label: "17:00", value: "17:00" },
  { label: "17:30", value: "17:30" },
  { label: "18:00", value: "18:00" },
  { label: "18:30", value: "18:30" },
  { label: "19:00", value: "19:00" },
  { label: "19:30", value: "19:30" },
  { label: "20:00", value: "20:00" },
  { label: "20:30", value: "20:30" },
  { label: "21:00", value: "21:00" },
];