import type { Metadata } from "next"; 
import "./globals.css";
import AntdThemeProvider from "@/providers/AntdThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { connectToDB } from "@/config/dbConnect";
import CustomLayout from "@/custom-layout/page";

 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await connectToDB();
  return (
     <ClerkProvider>
    <html lang="en">     
      <body>      
        <AntdThemeProvider>
          <CustomLayout>
            {children}
          </CustomLayout>
        
        </AntdThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
